name: CI

on:
  push:
    branches: [ master ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2
      - name: Info
        run: |
          echo GITHUB_REF: ${env:GITHUB_REF}

  pre-release:
    name: "Pre Release"
    runs-on: ubuntu-latest
    needs: build
    if: false && startsWith(github.ref, 'refs/tags/') == false
    steps:
      - uses: "robinrottier/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE.txt
  
